// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Cn2f0G6aaGS5ZqQjRi_APJhOHbkn1TE',
    appId: '1:799535566215:web:23ce60ff56925058615722',
    messagingSenderId: '799535566215',
    projectId: 'udg-pokemon-app',
    authDomain: 'udg-pokemon-app.firebaseapp.com',
    storageBucket: 'udg-pokemon-app.firebasestorage.app',
    measurementId: 'G-N84YZEL716',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilhH8vZZjS3KvsH5_obL9wALel1cG2rI',
    appId: '1:799535566215:android:e97e834308e14b74615722',
    messagingSenderId: '799535566215',
    projectId: 'udg-pokemon-app',
    storageBucket: 'udg-pokemon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWrkvxvj8bbUyL1Ny0pC8dlAHJgIN1H6U',
    appId: '1:799535566215:ios:e5d9c45ffa4b29f5615722',
    messagingSenderId: '799535566215',
    projectId: 'udg-pokemon-app',
    storageBucket: 'udg-pokemon-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWrkvxvj8bbUyL1Ny0pC8dlAHJgIN1H6U',
    appId: '1:799535566215:ios:e5d9c45ffa4b29f5615722',
    messagingSenderId: '799535566215',
    projectId: 'udg-pokemon-app',
    storageBucket: 'udg-pokemon-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Cn2f0G6aaGS5ZqQjRi_APJhOHbkn1TE',
    appId: '1:799535566215:web:861d8a14a269fa5c615722',
    messagingSenderId: '799535566215',
    projectId: 'udg-pokemon-app',
    authDomain: 'udg-pokemon-app.firebaseapp.com',
    storageBucket: 'udg-pokemon-app.firebasestorage.app',
    measurementId: 'G-6FRD2820J3',
  );
}
